version: '3'

services:
  primary-backend:
    build: ./primary-backend
    ports:
      - "3000:3000"
    env_file:
      - ./primary-backend/.env
    depends_on:
      - kafka
    restart: unless-stopped

  hook:
    build: ./hook
    ports:
      - "3002:3002"
    env_file:
      - ./hook/.env
    depends_on:
      - kafka
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
    depends_on:
      - primary-backend
    restart: unless-stopped

  worker:
    build: ./worker
    env_file:
      - ./worker/.env
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

  processor:
    build: ./processor
    env_file:
      - ./processor/.env
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_HEAP_OPTS: "-Xmx128M -Xms128M"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    restart: unless-stopped